service: take-blip-challenge

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  getRepositories:
    handler: src/Api/handler.getRepositories
    events:
      - http:
          path: /repositorios-takeblip
          method: GET

custom:  
  serverless-offline:
    host: 0.0.0.0
    port: 3000

plugins:
  - serverless-offline
